version: '2'
services:
  demo-app:
    image: demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://demo-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://demo-elasticsearch:9200
  demo-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: demo-elasticsearch
